---
title: "overview"
description: |
  Summary information about all data for all outcomes.
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r message=FALSE,eval=TRUE}
library(targets)
library(tidyverse)
library(dontpanic)
library(happypillpain)
library(janitor)
library(gt)
library(RColorBrewer)
library(glue)

```

```{r}
withr::with_dir(here::here(), {
  tar_load(hpp_models_nomod_arm)
})

```



# chronic pain conditions

```{r}
  map_df(hpp_models_nomod_arm,
       .f = function(mod){
    mod %>% 
      pluck("agd_arm") %>% 
      group_by(chronic_condition) %>% 
      summarise(
        studies = n_distinct(.study)
      ) %>% 
      arrange(desc(studies)) %>% 
      head(5) %>% 
      mutate(outcome = mod %>% pluck('hpp_outcome'))
  }) %>% 
  gt(groupname_col = "outcome")

```


# main aim

```{r}


```



# old stuff

```{r warning=FALSE}
hpp_dat <-
  # latest dataset
  raw_hpp_dat_path() %>%
  read_csv(col_types = cols(.default = "c")) %>% 
  # make code friendly
  preliminary_scrub()

meta_var <- read_rds("data-raw/meta_var.rds")

keywords <-
  read_csv("data-raw/keywords.csv")

```

```{r }
current_n_studies <- 
   hpp_dat %>%
    dplyr::pull(study_identifier) %>%
    dplyr::n_distinct()

```

As of `r Sys.Date() %>% title_date()`, the analysis currently includes `r current_n_studies` out of an expected `r meta_var$total_studies` studies.

```{r fig.height=2}


tribble(
  ~stage,            ~count,
  "analysis",  current_n_studies,
  "extraction", meta_var$total_studies - current_n_studies
) %>% 
  mutate(studies = "studies",
         stage = fct_relevel(stage, "extraction")) %>%
  ggplot() +
  geom_col(
        aes(studies, y = count, fill = stage)) +
  coord_flip() +
  rockthemes::scale_fill_nodoubt() +
  theme_minimal() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank()) +
  labs(
    title = "Current progress of data extraction"
  )


```

## overview



### intervention class


```{r}
drugs_class <- 
hpp_dat %>%
  pull(intervention_class) %>%
  unique() %>%
  tibble(intervention_class = .) %>%
  mutate(antidepressants = map_chr(
    intervention_class,
    .f = function(int_class) {
      hpp_dat %>%
        dplyr::filter(intervention_class == int_class) %>%
        pull(intervention_drug) %>%
        unique() %>%
        paste0(collapse = "; ")
    }
  )
  )


```

```{r}


int_tabdat <- 

hpp_dat %>%
  dplyr::filter(intervention != "Placebo") %>%
  dplyr::mutate(intervention_class = if_else(
    is.na(intervention_class),
    "not an antidepressant",
    intervention_class
  )) %>%
  group_by(intervention_class) %>%
  summarise(n_studies = n_distinct(study_identifier),
            n_drugs = n_distinct(intervention_drug)) %>%
  arrange(desc(n_studies)) %>%
  left_join(drugs_class, by = "intervention_class") 

int_gt <- 
int_tabdat %>%
  gt() %>%
  data_color(
    columns = vars(n_studies),
    colors = scales::col_numeric(palette = "Blues",
                                 domain = NULL)
  ) %>%
  data_color(
    columns = vars(n_drugs),
    colors = scales::col_numeric(palette = "Greens",
                                 domain = NULL)
  ) %>%
  
  # data_color(columns = vars(intervention_class)#,
  #            #colors = "#bdbdbd"
  #            ) %>%
  cols_label(intervention_class = "intervention type",
             n_studies = "number of studies", 
             n_drugs = "number of antidepressants") 

int_gt %>% 
  hpp_gt_pal("intervention_class")



```

### Number of studies by chronic pain condition


```{r}
hpp_dat %>% 
  group_by(chronic_pain_condition_s) %>% 
  summarise(
    n_studies = n_distinct(study_identifier),
    n_interventions = n_distinct(intervention)
  ) %>% 
  arrange(desc(n_studies), desc(n_interventions)) %>% 
  gt(
  ) %>% 
  data_color(
    columns = vars(n_studies),
    colors = scales::col_numeric(
      palette = "Blues",
      domain = NULL
    )
  ) %>%
  
  data_color(
    columns = vars( n_interventions),
    colors = scales::col_numeric(
      palette = "Greens",
      domain = NULL
    )
  ) %>%
  
  cols_label(
    chronic_pain_condition_s = "Chronic pain condition",
    n_studies = "Number of studies",
    n_interventions = "Number of interventions"
  ) %>% 
  hpp_gt_pal("chronic_pain_condition_s")

```

### Number of studies by class

```{r}
#  todo: group interventions by type 

hpp_dat %>% 
  filter(intervention_drug != "placebo") %>% 
  group_by(intervention_drug, intervention_type) %>% 
  summarise(
    n_studies = n_distinct(study_identifier),
    n_dosages = n_distinct(intervention)
  ) %>% 
  arrange(desc(n_studies)) %>% 
  gt(
    rowname_col = "intervention",
    groupname_col = "intervention_type"
  ) %>% 
   data_color(
    columns = vars(n_studies),
    colors = scales::col_numeric(
      palette = c("Blues"),
      domain = NULL
    )
  ) %>% 
  data_color(
    columns = vars(n_dosages),
    colors = scales::col_numeric(
      palette = "Greens",
      domain = NULL
    )
  ) %>%
  summary_rows(
    groups = TRUE,
    columns = vars(n_studies, n_dosages),
    fns = list(total = ~sum(.))
  ) %>% 
  cols_label(intervention_drug = "intervention",
             n_studies = "number of studies",
             n_dosages = "number of dosages") %>% 
  hpp_gt_pal("intervention_drug") 



```

### multi-armed studies

```{r}
hpp_dat %>% 
  select(study_identifier, intervention, intervention_drug, main_aim_pain_mood_quality_of_life_etc) %>% 
  group_by(main_aim_pain_mood_quality_of_life_etc, study_identifier) %>% 
  summarise(
    n_interventions = n_distinct(intervention_drug)
  ) %>% 
  filter(n_interventions > 2) %>% 
  mutate(
    interventions = map_chr(
      study_identifier,
      .f = function(id) {
        hpp_dat %>% 
          dplyr::filter(study_identifier == id) %>% 
          pull(intervention_drug) %>% 
          paste0(collapse = "; ")
      }
    )
  ) %>%
  arrange(desc(n_interventions)) %>% 
  gt() %>% 
  cols_label(
    study_identifier = "study",
    n_interventions = "number of interventions"
  ) %>% 
  hpp_gt_pal("study_identifier")


```

### Frequency of comparisons 

