---
title: "data"
description: |
  Data used in the analysis
output: distill::distill_article
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```


```{r}
library(tidyverse)
library(gt)
library(RColorBrewer)
library(happypillpain)

```


### the data


```{r wrangle to model inputs}

netdat <- read_rds("outputs/netdat/pain_netdat.rds")

```

```{r include=FALSE}
# check that there are not multiple measures per study
(netdat %>% 
  count(study_arm_id, mean) %>% 
  filter(n  > 1) %>% 
  nrow()) == 0

# thank goodness

```


```{r}
tabledat <- 
  netdat %>% 
  select(study, arm, intervention, scale, mean, se, n, intervention_type) 
```

```{r fig.width=10}

plotdat <- 
tabledat %>% 
  arrange(study, intervention_type, intervention, mean, n) %>% 
  mutate(
    sd = sqrt(n) * se,
    lower = mean - qnorm(0.025) * se,
    upper = mean + qnorm(0.975),
    intervention_type = fct_relevel(tolower(intervention_type), "placebo"),
    scale = fct_relevel(scale, "not matched", after = Inf)
  ) %>% 
  select(study, lower, upper, type = intervention_type, intervention, arm, mean, sd, n, scale) 


```

```{r}

 plotdat %>%  
  gt(groupname_col = "scale", 
     rowname_col = "study") %>% 
  data_color(
    columns = vars(type),
    colors = scales::col_factor(
      palette = "Blues", 
      domain = NULL
    )
  ) %>% 
  data_color(
    columns = vars(lower, upper, mean, n),
    colors = scales::col_numeric(
      palette = "Greens",
      domain = NULL
    )
  ) %>% 
  data_color(
    columns = vars(sd),
    colors = scales::col_numeric(
      palette = "Greys",
      domain = NULL
    )
  ) %>% 
  fmt_number(
    columns = vars(lower, upper, mean, sd),
    decimals = 2
  ) %>% 
  tab_options(
    row_group.background.color = "gray"
  ) %>% 
  tab_spanner(
    label = "Confidence interval",
    columns = vars("lower", "upper")
  ) %>% 
  tab_spanner(
    label = "Intervention",
    columns = vars("type", "intervention", "arm")
  ) %>% 
  tab_spanner(
    label = "Summary statistics",
    columns = vars("mean", "sd", "n")
  ) %>% 
  hpp_gt_pal(
    "study"
  )


```

